src.training_scripts.train_echo:
  source_bart_model_name: eugenesiow/bart-paraphrase
  sentence_transformer_similarity_evaluator_name: flax-sentence-embeddings/all_datasets_v4_MiniLM-L6
  train_split_path: data/sst2/train.csv
  eval_split_path: data/sst2/validation.csv
  min_len: 8
  max_len: 32
  batch_size: 1
  n_epochs: 1
  lr: 1e-6
  dpo_beta: 0.1
  temperature: 1
  n_max_train_samples_per_epoch: 1024
  echo_runs_save_dir: runs/echo/
  training_log_filename: log.txt

src.training_scripts.train_attacker:
  source_bart_model_name: eugenesiow/bart-paraphrase
  source_bart_weights_path: runs/echo/run_0/checkpoints/best.pt
  reference_bart_weights_path: null
  sentence_transformer_similarity_evaluator_name: flax-sentence-embeddings/all_datasets_v4_MiniLM-L6
  train_split_path: data/sst2/train.csv
  eval_split_path: data/sst2/validation.csv
  min_len: 8
  max_len: 32
  batch_size: 4
  n_epochs: 4
  lr: 1e-6
  dpo_beta: 0.1
  temperature: 1
  n_max_train_samples_per_epoch: 1024
  attacker_runs_save_dir: runs/attacker/
  training_log_filename: log.txt
  target_label: negative

src.training_scripts.retrain_victim_statically:
  static_victim_retraining_runs_save_dir: runs/static_victim_retraining/
  attacker_run_dir: runs/attacker/run_n/  # to take the adversarial examples from
  original_train_split_path: data/sst2/train.csv
  original_eval_split_path: data/sst2/validation.csv
  min_len: 12
  max_len: 32
  batch_size: 4
  n_epochs: 10
  lr: 1e-5
  target_label: negative