src.train_echo:
  source_bart_model_name: eugenesiow/bart-paraphrase
  sentence_transformer_similarity_evaluator_name: flax-sentence-embeddings/all_datasets_v4_MiniLM-L6
  train_split_path: data/sst2/train.csv
  eval_split_path: data/sst2/validation.csv
  min_len: 8
  max_len: 32
  batch_size: 1
  n_epochs: 1
  lr: 1e-5
  dpo_beta: 0.1
  temperature: 1
  n_max_train_samples_per_epoch: 1024
  echo_runs_save_dir: runs/echo/
  training_log_filename: log.txt